### ISSUE TITLE
Error during import

### ISSUE THREAD

**Issue by frenkiboy** [canzarlab/JVis-learn#1]
Dear Developers, 

I am getting the following error during 

```import Jvis```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vfranke/bin/Software/miniconda3/envs/jvis/lib/python3.6/site-packages/Jvis/__init__.py", line 1, in <module>
    from .jumap_ import UMAP, JUMAPBASE, JUMAP
  File "/home/vfranke/bin/Software/miniconda3/envs/jvis/lib/python3.6/site-packages/Jvis/jumap_.py", line 30, in <module>
    import Jvis.distances as dist
AttributeError: module 'Jvis' has no attribute 'distances'
```

Best

**Comment by vanhoan310** [comment]
Dear Frenkiboy,

this might be relevant. 
https://github.com/lmcinnes/umap/issues/173

Let me know if you can fix it.

**Comment by vanhoan310** [comment]
and you need to install scikit-learn version >= 0.23.0
