### ISSUE TITLE
Error during import 2

### ISSUE THREAD

**Issue by neuro30** [canzarlab/JVis-learn#2]
Hi, I am getting the following error:

` from Jvis import JUMAP, JTSNE`

```
Traceback (most recent call last):
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\errors.py", line 744, in new_error_context
    yield
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 328, in lower_inst
    self.storevar(val, inst.target.name)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 1278, in storevar
    raise AssertionError(msg)
AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\Jvis\__init__.py", line 1, in <module>
    from .jumap_ import UMAP, JUMAPBASE, JUMAP
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\Jvis\jumap_.py", line 55, in <module>
    from Jvis.layouts import (
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\Jvis\layouts.py", line 39, in <module>
    def rdist(x, y):
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\decorators.py", line 221, in wrapper
    disp.compile(sig)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 106, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 395, in _compile_core
    raise e
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler_machinery.py", line 339, in run
    raise patched_exception
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\typed_passes.py", line 463, in run_pass
    NativeLowering().run_pass(state)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\typed_passes.py", line 384, in run_pass
    lower.lower()
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Storing i64 to ptr of i32 ('dim'). FE type int32

File "lib\site-packages\Jvis\layouts.py", line 52:
def rdist(x, y):
    <source elided>
    result = 0.0
    dim = x.shape[0]
    ^

During: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at C:\Users\neuro\AppData\Local\Programs\Python\Python39\lib\site-packages\Jvis\layouts.py (52)
```

**Comment by qiaochen** [comment]
It works after I downgrading numba from 0.53.1 to 0.52.0.
